# Meta Data for SEO

## Homepage
title = "Dseqr"
titleSeparator = "-"
titleAddition = "RNA-Seq Analysis"
description = "Dseqr runs multi-sample single-cell and bulk RNA-seq analyses from fastq → pathways → hits."

## Open Graph + Twitter Cards
images = ["hiv-in-blood-plasma-david-goodsell.png"]
twitterSite = "alexvpickering"
twitterCreator = "alexvpickering"
facebookAuthor = "alexvpickering"
facebookPublisher = "alexvpickering"
ogLocale = "en_US"

## JSON-LD
schemaType = "Dseqr"
schemaLogo = "logo-dseqr.png"
schemaTwitter = "https://twitter.com/alexvpickering"
schemaLinkedIn = "https://www.linkedin.com/in/alexvpickering/"
schemaGitHub = "https://github.com/alexvpickering"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = true
alertText = "Like Dseqr? <a class=\"alert-link\" href=\"https://github.com/hms-dbmi/dseqr/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/hms-dbmi/dseqr.docs"
editPage = true
